'use client';

import { useMemo, useState } from 'react';

type Tab = 'listing' | 'claims' | 'assets' | 'data' | 'policy' | 'rejection' | 'release';

function downloadCanvas(canvas: HTMLCanvasElement, filename: string) {
  const link = document.createElement('a');
  link.download = filename;
  link.href = canvas.toDataURL('image/png');
  link.click();
}

function ListingTool() {
  const [title,setTitle]=useState(''); const [short,setShort]=useState(''); const [full,setFull]=useState('');
  const errors = useMemo(() => {
    const out:string[]=[];
    if(!title.trim() || title.length>30) out.push('Title must be 1–30 characters.');
    if(!short.trim() || short.length>80) out.push('Short description must be 1–80 characters.');
    if(!full.trim() || full.length>4000) out.push('Full description must be 1–4000 characters.');
    return out;
  },[title,short,full]);
  const risky = /#1|number\s*1|best app|guaranteed|official|100% secure|bank.?grade|completely offline/i.test(`${title} ${short} ${full}`);
  return <div className="toolGrid">
    <div className="toolCard"><h3>Play Store listing</h3><p>Draft or paste your listing. Length checks do not prove that the claims are true.</p>
      <label>App title ({title.length}/30)</label><input value={title} onChange={e=>setTitle(e.target.value)} />
      <label>Short description ({short.length}/80)</label><textarea value={short} onChange={e=>setShort(e.target.value)} />
      <label>Full description ({full.length}/4000)</label><textarea value={full} onChange={e=>setFull(e.target.value)} />
    </div>
    <div className="toolCard"><h3>Listing gate</h3>{errors.length?<div className="warningBox"><strong>Fix before submission</strong><ul>{errors.map(x=><li key={x}>{x}</li>)}</ul></div>:<div className="successBox">Character limits pass.</div>}
      {risky&&<div className="warningBox" style={{marginTop:10}}>Potential ranking, affiliation, guarantee, security, or absolute-functionality claim detected. Require evidence before publishing.</div>}
      <p className="truthNote">A valid listing must describe only functionality that exists in the release users will receive.</p>
    </div>
  </div>;
}

function ClaimsTool(){
  const [claim,setClaim]=useState(''); const [evidence,setEvidence]=useState(''); const [contradiction,setContradiction]=useState(''); const [highImpact,setHighImpact]=useState(false);
  const status = contradiction.trim()?'CONTRADICTED':evidence.trim()?'VERIFIED':highImpact?'UNVERIFIED':'UNVERIFIED';
  const publishable=status==='VERIFIED';
  return <div className="toolGrid"><div className="toolCard"><h3>Claim verification</h3><p>Use this before putting a statement in the store listing, screenshots, privacy material, or release notes.</p>
    <label>Claim</label><textarea value={claim} onChange={e=>setClaim(e.target.value)} placeholder="Example: Translation works fully offline" />
    <label>Supporting evidence</label><textarea value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Repository path, runtime test, compiled evidence, Play state…" />
    <label>Contradicting evidence</label><textarea value={contradiction} onChange={e=>setContradiction(e.target.value)} />
    <div className="checkRow"><input type="checkbox" checked={highImpact} onChange={e=>setHighImpact(e.target.checked)}/><span>High-impact claim (privacy, security, Data Safety, affiliation, audience, policy)</span></div>
  </div><div className="toolCard"><h3>Decision</h3><p><span className="pill">{status}</span></p><p><strong>Publishable:</strong> {publishable?'Yes, based on supplied evidence':'No'}</p>{contradiction&&<div className="warningBox">Contradicted claims are blocked. Fix the app or the claim; do not conceal the contradiction.</div>}{!evidence&&!contradiction&&<div className="warningBox">No authoritative supporting evidence supplied.</div>}</div></div>;
}

function AssetsTool(){
  const [appName,setAppName]=useState('My App'); const [initials,setInitials]=useState(''); const [tagline,setTagline]=useState(''); const [headline,setHeadline]=useState(''); const [screenshot,setScreenshot]=useState<File|null>(null);
  function makeIcon(){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d')!;x.fillStyle='#1f2937';x.fillRect(0,0,512,512);x.fillStyle='#fff';x.font='700 180px Arial';x.textAlign='center';x.textBaseline='middle';const letters=(initials.trim()||appName.split(/\s+/).slice(0,2).map(v=>v[0]||'').join('')).slice(0,3).toUpperCase()||'A';x.fillText(letters,256,260);downloadCanvas(c,'play-icon-512.png')}
  function makeFeature(){const c=document.createElement('canvas');c.width=1024;c.height=500;const x=c.getContext('2d')!;x.fillStyle='#172b4d';x.fillRect(0,0,1024,500);x.fillStyle='#fff';x.font='700 62px Arial';x.fillText(appName.slice(0,30),70,230);x.font='30px Arial';x.fillStyle='#dce8ff';x.fillText(tagline.slice(0,55),72,292);downloadCanvas(c,'feature-graphic-1024x500.png')}
  async function compose(){if(!screenshot) return;const img=new Image();img.src=URL.createObjectURL(screenshot);await img.decode();const c=document.createElement('canvas');c.width=1080;c.height=1920;const x=c.getContext('2d')!;x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.fillStyle='#111827';x.font='700 50px Arial';x.textAlign='center';x.fillText(headline.slice(0,55),540,125);const maxW=900,maxH=1550,scale=Math.min(maxW/img.width,maxH/img.height);const w=img.width*scale,h=img.height*scale;x.drawImage(img,(1080-w)/2,250,w,h);downloadCanvas(c,'play-screenshot.png');URL.revokeObjectURL(img.src)}
  return <div className="toolGrid"><div className="toolCard"><h3>Generate basic Play assets</h3><label>App name</label><input value={appName} onChange={e=>setAppName(e.target.value)}/><label>Initials (optional)</label><input value={initials} onChange={e=>setInitials(e.target.value)}/><label>Feature graphic tagline</label><input value={tagline} onChange={e=>setTagline(e.target.value)}/><div className="row" style={{marginTop:12}}><button className="primaryButton" onClick={makeIcon}>Generate 512×512 icon</button><button className="primaryButton" onClick={makeFeature}>Generate 1024×500 graphic</button></div><p className="muted">These are simple original assets. If an exact brand logo is required, use the real approved logo rather than inventing one.</p></div>
  <div className="toolCard"><h3>Compose a truthful screenshot</h3><p>Upload a real app screenshot. The website only adds a background/headline; it does not fabricate app UI.</p><label>Headline</label><input value={headline} onChange={e=>setHeadline(e.target.value)}/><label>Real screenshot</label><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setScreenshot(e.target.files?.[0]||null)}/><button className="primaryButton" style={{marginTop:12}} onClick={compose} disabled={!screenshot}>Compose 1080×1920 screenshot</button></div></div>;
}

function DataSafetyTool(){
 const [ads,setAds]=useState(false),[analytics,setAnalytics]=useState(false),[auth,setAuth]=useState(false),[remote,setRemote]=useState(false),[location,setLocation]=useState(false),[health,setHealth]=useState(false),[financial,setFinancial]=useState(false),[deletion,setDeletion]=useState(false); const questions:string[]=[];
 if(ads)questions.push('What ad SDK is used, what identifiers/data does it collect, and is advertising personalized?'); if(analytics)questions.push('What analytics data and identifiers are collected, retained, or shared?'); if(auth)questions.push('What account identifiers are processed and can users delete accounts/data?'); if(remote)questions.push('What user data is sent to remote APIs/AI services and why?'); if(location)questions.push('Is location approximate/precise/background, optional or required, and what feature needs it?'); if(health)questions.push('Which health data types are handled and under which Google Play health requirements?'); if(financial)questions.push('What financial functionality or data is handled and which declaration applies?');
 return <div className="toolGrid"><div className="toolCard"><h3>Data Safety evidence questionnaire</h3><p>Check only what is actually present. This prepares questions; it does not fabricate a Data Safety declaration.</p><div className="checkList">{[['Ads',ads,setAds],['Analytics',analytics,setAnalytics],['User accounts/authentication',auth,setAuth],['Remote APIs / AI / cloud processing',remote,setRemote],['Location',location,setLocation],['Health data/features',health,setHealth],['Financial data/features',financial,setFinancial],['Account/data deletion mechanism established',deletion,setDeletion]].map(([label,value,setter])=><label className="checkRow" key={String(label)}><input type="checkbox" checked={value as boolean} onChange={e=>(setter as (v:boolean)=>void)(e.target.checked)}/><span>{String(label)}</span></label>)}</div></div><div className="toolCard"><h3>Required evidence</h3>{questions.length?<ol>{questions.map(q=><li key={q}>{q}</li>)}</ol>:<p className="muted">Select the app behaviors that apply.</p>}{auth&&!deletion&&<div className="warningBox">Account functionality is selected but deletion is not established. Verify current Play account-deletion requirements before submission.</div>}<p className="truthNote">SDK detection is a clue; Data Safety must reflect actual production collection, sharing, processing, and retention.</p></div></div>;
}

function PolicyTool(){
 const [target,setTarget]=useState('36'),[privacy,setPrivacy]=useState(false),[reviewer,setReviewer]=useState(false),[login,setLogin]=useState(false),[audience,setAudience]=useState(false),[content,setContent]=useState(false),[testing,setTesting]=useState(false);
 const blockers:string[]=[];if(Number(target)<36)blockers.push('Standard mobile new apps/updates should be checked against the current API 36 submission baseline.');if(!privacy)blockers.push('Public privacy-policy status is not confirmed.');if(login&&!reviewer)blockers.push('Login is required but reviewer access is not confirmed.');if(!audience)blockers.push('Target audience/content declaration is not confirmed.');if(!content)blockers.push('Content rating/declarations are not confirmed.');if(!testing)blockers.push('Testing/production-access requirements are not confirmed.');
 return <div className="toolGrid"><div className="toolCard"><h3>Policy/readiness gate</h3><label>Target SDK</label><input value={target} onChange={e=>setTarget(e.target.value)} inputMode="numeric"/><div className="checkList">{[['Public privacy policy confirmed',privacy,setPrivacy],['App requires login',login,setLogin],['Reviewer access/instructions established',reviewer,setReviewer],['Target audience declaration reviewed',audience,setAudience],['Content rating and applicable declarations reviewed',content,setContent],['Testing / production access requirement reviewed',testing,setTesting]].map(([l,v,s])=><label className="checkRow" key={String(l)}><input type="checkbox" checked={v as boolean} onChange={e=>(s as (v:boolean)=>void)(e.target.checked)}/><span>{String(l)}</span></label>)}</div></div><div className="toolCard"><h3>Readiness</h3>{blockers.length?<div className="warningBox"><strong>Not ready to call submission-ready</strong><ul>{blockers.map(x=><li key={x}>{x}</li>)}</ul></div>:<div className="successBox">No blocker is indicated by this questionnaire. Recheck live Google Play policy before submission.</div>}<p className="muted">This does not predict Google’s proprietary review outcome.</p></div></div>;
}

function RejectionTool(){const [notice,setNotice]=useState('');const classification=useMemo(()=>{const t=notice.toLowerCase();if(!t)return null;if(/data safety|data collection|data shared/.test(t))return ['Data Safety / privacy','Compare the rejection notice with SDK/runtime evidence, privacy policy, and Data Safety answers. Correct the underlying mismatch before resubmission.'];if(/permission|sms|call log|background location|accessibility/.test(t))return ['Sensitive permission','Identify the exact permission, prove the qualifying core use case or remove it, then update declarations/evidence.'];if(/target api|target sdk/.test(t))return ['Target API','Update the release build to the required target API unless an applicable current exception/extension exists.'];if(/metadata|description|screenshot|icon|store listing/.test(t))return ['Store metadata','Find the unsupported/misleading asset or claim, align it with actual functionality, and replace it with truthful metadata.'];if(/deceptive|misleading|hidden|review|behavior/.test(t))return ['Deceptive behavior / review integrity','Do not hide functionality or create reviewer-only behavior. Correct the product behavior and declarations, then provide factual evidence.'];if(/app access|login|credential/.test(t))return ['App access','Provide working reviewer instructions/credentials for the actual production-like app experience.'];return ['Needs policy mapping','Preserve the exact notice, identify the policy URL/category, affected release and evidence before deciding on a fix or appeal.'];},[notice]);return <div className="toolGrid"><div className="toolCard"><h3>Google Play rejection triage</h3><p>Paste the exact rejection text. Do not paraphrase away details.</p><textarea value={notice} onChange={e=>setNotice(e.target.value)} placeholder="Paste the rejection notice here…"/></div><div className="toolCard"><h3>Initial triage</h3>{classification?<><p><strong>Likely category:</strong> {classification[0]}</p><p>{classification[1]}</p><div className="truthNote">Appeal only when factual evidence supports the appeal. Never conceal functionality or falsify declarations to pass review.</div></>:<p className="muted">Paste a notice to begin.</p>}</div></div>}

function ReleaseTool(){const items=['Release AAB corresponds to intended source/variant','Version code is higher than previous Play release','Target SDK meets current requirement','Signing / Play App Signing status is confirmed','Store listing describes only current functionality','Real screenshots correspond to current app experience','Privacy policy and Data Safety match production behavior','Sensitive permissions have qualifying use/evidence or are removed','Reviewer access works when login is required','Testing / production-access requirements are satisfied','Target audience/content rating/declarations are complete','Known policy blockers and unresolved material claims are cleared'];const [checked,setChecked]=useState<Record<number,boolean>>({});const done=items.filter((_,i)=>checked[i]).length;return <div className="toolGrid"><div className="toolCard"><h3>Release preparation</h3><div className="checkList">{items.map((x,i)=><label className="checkRow" key={x}><input type="checkbox" checked={!!checked[i]} onChange={e=>setChecked({...checked,[i]:e.target.checked})}/><span>{x}</span></label>)}</div></div><div className="toolCard"><h3>Release gate</h3><p><strong>{done}/{items.length}</strong> checks confirmed.</p>{done===items.length?<div className="successBox">Checklist complete. Validate the actual Play edit/release before committing.</div>:<div className="warningBox">Do not mark the release ready while {items.length-done} material check(s) remain unresolved.</div>}<p className="muted">Public website mode prepares releases; it does not publish to a developer’s Play account.</p></div></div>}

export default function PluginWorkspace(){const [tab,setTab]=useState<Tab>('listing');const tabs:Array<[Tab,string]>=[['listing','Play Listing'],['claims','Evidence & Claims'],['assets','Creative Assets'],['data','Data Safety'],['policy','Policy Readiness'],['rejection','Rejection Triage'],['release','Release']];return <section className="workspace"><h2>Full deployment workspace</h2><p className="workspaceIntro">These are the same workflow areas represented by the plugin skills. Website and plugin follow the same rule: inspect first, distinguish evidence from inference, and never make a false claim just to pass review.</p><div className="tabs">{tabs.map(([id,label])=><button key={id} className={`tabButton ${tab===id?'active':''}`} onClick={()=>setTab(id)}>{label}</button>)}</div>{tab==='listing'&&<ListingTool/>}{tab==='claims'&&<ClaimsTool/>}{tab==='assets'&&<AssetsTool/>}{tab==='data'&&<DataSafetyTool/>}{tab==='policy'&&<PolicyTool/>}{tab==='rejection'&&<RejectionTool/>}{tab==='release'&&<ReleaseTool/>}</section>}
